### ISSUE TITLE
Improperly escaped double-quotes

### ISSUE THREAD

**Issue by ghost** [themarshallproject/city-crime#1]
Lines 932 & 947 use `\"` to escape a double quote when the proper escape protocol in CSV files for double quotes is to use `""`

That means line 932 should be:

```
"FL01306",1988,"Miami",389720,146,411,6398,6006,12961,0,3325.72103048342,37.4627938006774,105.460330493688,1641.69147079955,1541.10643538951,"Miami Herald","""MAJOR CRIMES UP MOST IN 4 YEARS,"" March 11, 1989, Miami Herald via Nexis"
```

and line 947 should be:

```
"PAPEP00",1988,"Philadelphia",1657285,374,912,8858,6938,17082,12,1030.72193376516,22.567029810805,55.0297625332999,534.488636535056,418.636504886003,NA,NA
```

Given the importance of the article & data I didn't want to make a PR (you'll probably have folks trying to manipulate the data that way).

You can validate the improper escaping by trying to read the data into R with `read.csv()`. Those two rows will have `NA` for the year.

Also, `readr::read_csv()` — which implements far stricter but also more proper CSV parsing rules — gives the following two warnings (it had two more but the above fixes that):

``` r
Warning: 2 parsing failures.
row col           expected     actual
922 url delimiter or quote C         
922 NA  17 columns         20 columns
```

**Comment by tommeagher** [comment]
Thank you for flagging this issue. We'll take a look.
